-- =============================================================================
-- 0010 — Web accounts, the credit wallet, and web chat threads
--
-- This migration turns a WhatsApp-only product into one with a signed-in web
-- application beside it. Three separate things are happening, and they are
-- worth reading in order because each depends on the one before it.
--
-- ## 1. An account is no longer a phone number
--
-- `users.phone_number` was UNIQUE NOT NULL, so the row and the handset were the
-- same fact. A web signup has no phone number at all, which that constraint
-- makes impossible to express. It becomes nullable, and a CHECK enforces the
-- thing actually required: an account must be reachable by *something* — a
-- phone number, an email address, or a federated identity.
--
-- Nullable UNIQUE is the correct shape here rather than a workaround. Postgres
-- treats NULLs as distinct, so any number of phone-less web accounts coexist
-- while a real number is still unique across the table, and the existing
-- `ON CONFLICT (phone_number)` upsert in UserRepository.findOrCreate keeps
-- working untouched.
--
-- ## 2. Credits become a ledger with two buckets
--
-- Until now "credits" were a daily counter in Redis mirrored to `daily_usage` —
-- a rate limit wearing the word credit. That is fine for throttling spend and
-- useless as an accounting record: it cannot answer "what did this advocate pay
-- for and what happened to it", which is the first question anyone asks once
-- money is involved.
--
-- `credit_ledger` is append-only and every balance change writes a row. The
-- balance is *also* denormalised onto `users` so a read is one indexed lookup
-- rather than a running sum, but `balance_after` on each row makes the two
-- reconcilable — if they ever disagree, the ledger is right and the cache is
-- wrong, and the disagreement is detectable instead of silent.
--
-- The two buckets are the part that matters for billing:
--
--   free_credits  — the daily allowance. Topped up to a fixed number each day,
--                   NOT accumulated. Yesterday's unused free credits are gone,
--                   which is what makes a daily allowance an allowance rather
--                   than an annuity.
--   paid_credits  — bought. Never expire, never reset, carried across days.
--
-- Spending draws down free first, then paid. Any other order would burn money
-- the advocate paid for while a free allowance expired unused beside it — the
-- kind of thing that produces support tickets and refund requests.
--
-- Collapsing these into one number is the mistake this design exists to avoid.
-- With a single balance, the nightly reset either wipes purchased credits or
-- lets free ones accumulate forever; there is no third option, and both are
-- wrong.
--
-- ## 3. Razorpay-shaped orders, with no gateway attached yet
--
-- `credit_orders` and `payment_events` model Razorpay's actual lifecycle. No
-- API calls are made anywhere in this build — but the schema commits to the
-- decisions that are expensive to change once rows exist:
--
--   - **Amounts are integer paise.** Razorpay's API is paise-denominated in
--     both directions. Storing rupees as NUMERIC means converting at every
--     boundary, and a division by 100 in the wrong place is a rounding error in
--     someone's money.
--   - **`receipt` is UNIQUE** and generated by us, so a double-submitted
--     checkout maps to one order rather than two.
--   - **Tax is broken out** at order time. Indian digital services attract GST,
--     and an invoice needs the base and tax components separately. Reconstructing
--     them later from a gross total is guesswork once the rate changes.
--   - **`payment_events` deduplicates webhooks.** Razorpay retries delivery
--     until it gets a 2xx, so `payment.captured` arriving three times is normal
--     operation, and crediting three times is not. Same defence as
--     `processed_webhooks` for Meta.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------

-- What moved credits, and in which direction. The kind is what makes the ledger
-- readable months later: a bare +5 says nothing, 'DAILY_GRANT' says everything.
DO $$ BEGIN
    CREATE TYPE credit_entry_kind AS ENUM (
        'DAILY_GRANT',    -- the free allowance, topped up once per day
        'SIGNUP_BONUS',   -- one-off welcome credits
        'ADMIN_GRANT',    -- granted by hand from the admin panel
        'PURCHASE',       -- paid for, via a settled credit_orders row
        'SPEND',          -- consumed by an action (negative)
        'REFUND',         -- an action was charged but never delivered (positive)
        'EXPIRY',         -- free credits cleared at the daily rollover (negative)
        'ADJUSTMENT'      -- manual correction; always carries a reason
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Which bucket an entry moved. Recorded per entry so a spend that straddles
-- both buckets is two rows, and neither is ambiguous about what it drew down.
DO $$ BEGIN
    CREATE TYPE credit_bucket AS ENUM ('FREE', 'PAID');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Razorpay's order lifecycle, plus the CREATED state that exists before the
-- gateway has seen it at all.
DO $$ BEGIN
    CREATE TYPE payment_order_status AS ENUM (
        'CREATED',    -- our row exists; checkout not yet completed
        'ATTEMPTED',  -- the gateway reports at least one payment attempt
        'PAID',       -- captured and credited
        'FAILED',     -- the attempt failed and will not be retried
        'REFUNDED'    -- money returned; credits clawed back
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- How an account came to exist. Purely descriptive, but it is the difference
-- between "web signups are flat" and "we have no idea where users come from".
DO $$ BEGIN
    CREATE TYPE account_source AS ENUM ('WHATSAPP', 'WEB_PASSWORD', 'WEB_GOOGLE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- =============================================================================
-- users — web identity columns
-- =============================================================================

-- The identity change described in the header. Dropped rather than replaced:
-- the UNIQUE index stays, and NULLs do not collide under it.
ALTER TABLE users ALTER COLUMN phone_number DROP NOT NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS email               VARCHAR(320);
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash       TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at   TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified_at   TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url          TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS signup_source       account_source NOT NULL DEFAULT 'WHATSAPP';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_web_login_at   TIMESTAMPTZ;

-- The wallet, denormalised. Authoritative for reads; credit_ledger is
-- authoritative for truth. See the header on why these are two columns.
ALTER TABLE users ADD COLUMN IF NOT EXISTS free_credits        INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS free_credits_date   DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS paid_credits        INTEGER NOT NULL DEFAULT 0;

-- Neither bucket may go negative. A spend that would breach this is a bug in
-- the spend function, and it should fail loudly at the constraint rather than
-- quietly hand out credit nobody has.
DO $$ BEGIN
    ALTER TABLE users ADD CONSTRAINT users_credits_non_negative
        CHECK (free_credits >= 0 AND paid_credits >= 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- An account has to be reachable somehow. Without this, a bug that nulls a
-- phone number produces a row nobody can ever sign into and nothing detects.
DO $$ BEGIN
    ALTER TABLE users ADD CONSTRAINT users_has_an_identity
        CHECK (phone_number IS NOT NULL OR email IS NOT NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Email uniqueness is enforced on the lowercased value, not the stored one.
-- Addresses are compared case-insensitively by every mail system on earth, so
-- a UNIQUE on the raw column would happily accept Advocate@example.com beside
-- advocate@example.com and hand the same person two accounts.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower
    ON users (lower(email)) WHERE email IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_users_signup_source ON users (signup_source);

COMMENT ON COLUMN users.email IS
    'Login address for the web app. Stored as entered; uniqueness is enforced on lower(email).';
COMMENT ON COLUMN users.password_hash IS
    'scrypt, encoded as scrypt$N$r$p$salt$hash. NULL for accounts that only ever signed in with Google or WhatsApp.';
COMMENT ON COLUMN users.free_credits IS
    'Daily allowance remaining today. Reset — not incremented — at the first action after midnight. See credit_refresh_free().';
-- "Paid" names the common case, but the property that matters is durability:
-- anything in this bucket survives the nightly rollover. Purchases land here,
-- and so do signup bonuses and admin grants, because a credit someone was given
-- as compensation expiring at midnight is the same broken promise as a
-- purchased one expiring.
COMMENT ON COLUMN users.paid_credits IS
    'Durable credits - purchased, bonus or granted. Never expire and never reset. Spent only after free_credits is exhausted.';
COMMENT ON COLUMN users.free_credits_date IS
    'The date free_credits belongs to. A value older than CURRENT_DATE means the bucket is stale and is refilled on next touch.';


-- =============================================================================
-- user_identities — federated logins
--
-- Separate from users because one account can legitimately have several: an
-- advocate who signs up with a password and later clicks "continue with Google"
-- must land on the *same* account, not a duplicate. The UNIQUE is on
-- (provider, provider_account_id) rather than on the email, because a Google
-- account's email can change while its `sub` cannot — matching on email would
-- silently detach the identity the day someone changes their address.
-- =============================================================================
CREATE TABLE IF NOT EXISTS user_identities (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    provider            VARCHAR(32) NOT NULL,        -- 'google'
    -- Google's `sub`. Stable for the life of the account, unlike the email.
    provider_account_id VARCHAR(255) NOT NULL,

    -- What the provider told us at link time. Kept for support ("which Google
    -- account is this?") and never used for matching.
    email               VARCHAR(320),
    display_name        VARCHAR(200),
    avatar_url          TEXT,

    last_login_at       TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (provider, provider_account_id)
);

CREATE INDEX IF NOT EXISTS idx_user_identities_user ON user_identities (user_id);


-- =============================================================================
-- web_sessions
--
-- Opaque random tokens, not JWTs. The admin panel uses a JWT because it has no
-- session store and one operator; end-user sessions have neither excuse. The
-- deciding property is revocation: a stolen JWT is valid until it expires and
-- nothing can stop it, whereas deleting a row here signs that device out on its
-- next request. "Sign out all devices" is a DELETE, not a key rotation.
--
-- Only the SHA-256 of the token is stored. A database leak therefore yields
-- nothing usable — the same reasoning as password hashing, applied to the
-- credential the token actually is.
-- =============================================================================
CREATE TABLE IF NOT EXISTS web_sessions (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- SHA-256 hex of the cookie value. Never the value itself.
    token_hash   CHAR(64) NOT NULL UNIQUE,

    -- Truncated and coarse on purpose: enough to show "Chrome on Windows,
    -- Mumbai" in a session list, not enough to be a tracking record.
    user_agent   VARCHAR(300),
    ip_address   INET,

    expires_at   TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_web_sessions_user   ON web_sessions (user_id, created_at DESC);
-- Partial: the expiry sweep only ever looks at sessions still considered live.
CREATE INDEX IF NOT EXISTS idx_web_sessions_expiry ON web_sessions (expires_at) WHERE revoked_at IS NULL;


-- =============================================================================
-- auth_tokens — email verification, password reset, phone linking
--
-- One table rather than three, because all three are the same object: a
-- single-use secret with an expiry, a purpose and a consumed-at timestamp.
-- Hashed for the same reason session tokens are — a reset token in a leaked
-- backup is an account takeover.
--
-- `consumed_at` rather than a DELETE so a user who clicks a reset link twice
-- gets "this link has already been used" instead of "invalid link", which reads
-- like an attack to a support agent and like a broken product to a user.
-- =============================================================================
CREATE TABLE IF NOT EXISTS auth_tokens (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    purpose     VARCHAR(32) NOT NULL,   -- EMAIL_VERIFY | PASSWORD_RESET | PHONE_LINK
    token_hash  CHAR(64) NOT NULL UNIQUE,

    -- Phone linking carries the number being claimed, so the code cannot be
    -- replayed against a different number than the one it was issued for.
    subject     VARCHAR(320),

    expires_at  TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    attempts    SMALLINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auth_tokens_user    ON auth_tokens (user_id, purpose);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_expiry  ON auth_tokens (expires_at) WHERE consumed_at IS NULL;


-- =============================================================================
-- credit_ledger — append-only
--
-- Never UPDATEd and never DELETEd outside the retention sweep. A correction is
-- a new compensating row, which is what makes the history reconstructable: an
-- edited ledger cannot answer "what did this look like on the 3rd".
-- =============================================================================
CREATE TABLE IF NOT EXISTS credit_ledger (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    kind          credit_entry_kind NOT NULL,
    bucket        credit_bucket     NOT NULL,

    -- Signed. Negative for SPEND and EXPIRY, positive for everything else.
    -- Deliberately not split into debit/credit columns: one signed integer
    -- cannot disagree with itself, and SUM(delta) is the balance by definition.
    delta         INTEGER NOT NULL,

    -- The bucket's balance immediately after this row was written. Makes the
    -- denormalised columns on `users` auditable without replaying the ledger.
    balance_after INTEGER NOT NULL,

    -- What was bought or spent: 'SECTION_LOOKUP', 'PRECEDENT_SEARCH', 'pack:500'.
    action        VARCHAR(60),
    -- Human-readable, shown in the user's own credit history.
    reason        TEXT,

    -- The idempotency key, and the reason this column is UNIQUE.
    --
    -- Every writer supplies one: 'daily:{user}:{date}', 'spend:{message_id}',
    -- 'order:{razorpay_payment_id}'. A retried webhook, a double-clicked send
    -- button or a re-run grant collides here and is rejected by the index
    -- rather than being applied twice. This is the single most important
    -- constraint in the table.
    reference     VARCHAR(200) UNIQUE,

    -- Set for PURCHASE and REFUND rows.
    order_id      UUID,

    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- A zero-delta entry is always a bug: either the caller meant to move
    -- credits and computed the amount wrong, or it should not have written a
    -- row at all.
    CONSTRAINT credit_ledger_delta_non_zero CHECK (delta <> 0)
);

CREATE INDEX IF NOT EXISTS idx_credit_ledger_user_time ON credit_ledger (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_credit_ledger_kind      ON credit_ledger (kind, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_credit_ledger_order     ON credit_ledger (order_id) WHERE order_id IS NOT NULL;


-- =============================================================================
-- credit_orders — Razorpay-shaped, gateway not yet attached
--
-- Amounts are INTEGER PAISE throughout. See the header for why this is not
-- NUMERIC rupees.
-- =============================================================================
CREATE TABLE IF NOT EXISTS credit_orders (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Our idempotency key, sent to Razorpay as `receipt`. Generated before the
    -- gateway is contacted, so a request that times out mid-flight can be
    -- retried without risking a second order.
    receipt            VARCHAR(64) NOT NULL UNIQUE,

    -- What the advocate gets. Fixed at order time so a later price change
    -- cannot alter what an already-paid order was worth.
    credits            INTEGER NOT NULL CHECK (credits > 0),
    pack_code          VARCHAR(40),

    -- Money, in paise. base + tax = amount_paise, enforced below.
    amount_paise       INTEGER NOT NULL CHECK (amount_paise > 0),
    base_paise         INTEGER NOT NULL CHECK (base_paise > 0),
    tax_paise          INTEGER NOT NULL DEFAULT 0 CHECK (tax_paise >= 0),
    -- Basis points, so 18% is 1800 and no fraction is lost to rounding.
    tax_rate_bps       INTEGER NOT NULL DEFAULT 0,
    currency           CHAR(3) NOT NULL DEFAULT 'INR',

    status             payment_order_status NOT NULL DEFAULT 'CREATED',

    -- Gateway identifiers. NULL until the corresponding step happens.
    razorpay_order_id  VARCHAR(64) UNIQUE,
    razorpay_payment_id VARCHAR(64) UNIQUE,
    -- The checkout signature, retained for dispute evidence.
    razorpay_signature VARCHAR(128),
    payment_method     VARCHAR(32),          -- upi | card | netbanking | wallet
    failure_reason     TEXT,

    -- Set when the PURCHASE ledger row is written, which is what makes
    -- "paid but not credited" a detectable state rather than an invisible one.
    credited_at        TIMESTAMPTZ,
    refunded_at        TIMESTAMPTZ,

    notes              JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- The invoice must add up. A mismatch here is an invoice that cannot be
    -- filed, and it is far cheaper to catch on INSERT than in an audit.
    CONSTRAINT credit_orders_amount_adds_up CHECK (base_paise + tax_paise = amount_paise)
);

CREATE INDEX IF NOT EXISTS idx_credit_orders_user   ON credit_orders (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_credit_orders_status ON credit_orders (status, created_at DESC);
-- Finds orders the gateway says are paid but which never produced credits.
CREATE INDEX IF NOT EXISTS idx_credit_orders_uncredited
    ON credit_orders (created_at) WHERE status = 'PAID' AND credited_at IS NULL;

DROP TRIGGER IF EXISTS trg_credit_orders_updated_at ON credit_orders;
CREATE TRIGGER trg_credit_orders_updated_at
    BEFORE UPDATE ON credit_orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Deferred rather than inline on credit_ledger, because the two tables
-- reference each other conceptually and one has to be created first.
DO $$ BEGIN
    ALTER TABLE credit_ledger ADD CONSTRAINT credit_ledger_order_fk
        FOREIGN KEY (order_id) REFERENCES credit_orders(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- =============================================================================
-- payment_events — webhook idempotency
--
-- Razorpay redelivers until it receives a 2xx, so the same `payment.captured`
-- arriving repeatedly is normal. Crediting on each delivery is not. Identical
-- in purpose to `processed_webhooks` for Meta, kept separate because the
-- lifetimes and the retention rules differ: a payment event is a financial
-- record and outlives a chat webhook by a long way.
-- =============================================================================
CREATE TABLE IF NOT EXISTS payment_events (
    -- Razorpay's `x-razorpay-event-id` header. The dedupe key.
    event_id     VARCHAR(120) PRIMARY KEY,
    event_type   VARCHAR(60) NOT NULL,
    order_id     UUID REFERENCES credit_orders(id) ON DELETE SET NULL,

    -- The verified body, kept verbatim. When a payment is disputed months
    -- later, what the gateway actually sent is the only account that matters.
    payload      JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- False when the signature verified but the event was not one we act on.
    handled      BOOLEAN NOT NULL DEFAULT FALSE,
    error_detail TEXT,

    received_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payment_events_time  ON payment_events (received_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_events_order ON payment_events (order_id);


-- =============================================================================
-- chat_threads / chat_messages — the web conversation
--
-- The WhatsApp side has no equivalent because WhatsApp *is* the thread; the web
-- app has a sidebar full of them, which means they need identity and ordering.
--
-- Not merged with `whatsapp_messages`: that table is a delivery log keyed on
-- Meta's message id, with delivery statuses and a 90-day retention. This is
-- conversation content the advocate expects to still be there next month.
-- Overloading one table with both would mean the retention sweep deleting
-- someone's research history.
-- =============================================================================
CREATE TABLE IF NOT EXISTS chat_threads (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Derived from the first message, editable by the user.
    title        VARCHAR(200) NOT NULL DEFAULT 'New chat',
    archived_at  TIMESTAMPTZ,

    -- Denormalised so the sidebar sorts without touching chat_messages.
    last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    message_count   INTEGER NOT NULL DEFAULT 0,

    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The sidebar query, exactly: this user's live threads, newest activity first.
CREATE INDEX IF NOT EXISTS idx_chat_threads_user
    ON chat_threads (user_id, last_message_at DESC) WHERE archived_at IS NULL;

DROP TRIGGER IF EXISTS trg_chat_threads_updated_at ON chat_threads;
CREATE TRIGGER trg_chat_threads_updated_at
    BEFORE UPDATE ON chat_threads
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


CREATE TABLE IF NOT EXISTS chat_messages (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id       UUID NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
    -- Denormalised from the thread so a user's own history can be read, and
    -- purged, without a join.
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    role            VARCHAR(12) NOT NULL CHECK (role IN ('user', 'assistant')),
    content         TEXT NOT NULL,

    -- What produced this answer. Everything below is NULL on a user message.
    intent          query_intent,
    citations       TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    -- Structured payload for renderable answers: precedent cards, case status.
    -- The web client can lay these out properly instead of parsing the
    -- WhatsApp-shaped text back into fields.
    structured      JSONB,

    model_used      VARCHAR(80),
    input_tokens    INTEGER NOT NULL DEFAULT 0,
    output_tokens   INTEGER NOT NULL DEFAULT 0,
    latency_ms      INTEGER NOT NULL DEFAULT 0,

    credits_charged INTEGER NOT NULL DEFAULT 0,
    guardrail_flagged BOOLEAN NOT NULL DEFAULT FALSE,
    guardrail_reason  TEXT,
    -- Set when generation failed. The message row still exists so the user sees
    -- what they asked and why it did not work, rather than their question
    -- vanishing.
    error_detail    TEXT,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_thread ON chat_messages (thread_id, created_at);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user   ON chat_messages (user_id, created_at DESC);


-- =============================================================================
-- Credit functions
--
-- The arithmetic lives in SQL rather than in the service layer, for one
-- reason: atomicity. Read-balance-then-write in application code is a race, and
-- the losing side of that race is either a double spend or a lost purchase.
-- `UPDATE ... RETURNING` under a row lock is atomic by construction, and two
-- concurrent requests serialise instead of interleaving.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- credit_refresh_free — roll the daily allowance over
--
-- Called at the start of every balance read and every spend. Idempotent within
-- a day: the guard on free_credits_date means the second call does nothing.
--
-- Expiry is recorded as its own ledger row before the top-up, so the history
-- reads honestly — "12 expired, 20 granted" rather than a bare "+8" that
-- implies the advocate was given eight credits.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION credit_refresh_free(
    p_user_id UUID,
    p_daily   INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_current   INTEGER;
    v_date      DATE;
    v_today     DATE := CURRENT_DATE;
BEGIN
    -- FOR UPDATE: two requests arriving at 00:00:00 must not both decide they
    -- are the one to refill, or the ledger gets two grants for one day.
    SELECT free_credits, free_credits_date
      INTO v_current, v_date
      FROM users
     WHERE id = p_user_id
       FOR UPDATE;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    -- Already refreshed today. The overwhelmingly common path.
    IF v_date IS NOT DISTINCT FROM v_today THEN
        RETURN;
    END IF;

    -- Yesterday's unused allowance lapses. Recorded rather than silently
    -- dropped: an advocate asking why their balance fell overnight deserves a
    -- row that says so.
    IF v_current > 0 AND v_date IS NOT NULL THEN
        INSERT INTO credit_ledger (user_id, kind, bucket, delta, balance_after, action, reason, reference)
        VALUES (
            p_user_id, 'EXPIRY', 'FREE', -v_current, 0, 'daily_rollover',
            format('%s unused free credit(s) from %s expired', v_current, v_date),
            format('expiry:%s:%s', p_user_id, v_date)
        )
        ON CONFLICT (reference) DO NOTHING;
    END IF;

    UPDATE users
       SET free_credits      = p_daily,
           free_credits_date = v_today
     WHERE id = p_user_id;

    IF p_daily > 0 THEN
        INSERT INTO credit_ledger (user_id, kind, bucket, delta, balance_after, action, reason, reference)
        VALUES (
            p_user_id, 'DAILY_GRANT', 'FREE', p_daily, p_daily, 'daily_allowance',
            format('Daily free allowance for %s', v_today),
            format('daily:%s:%s', p_user_id, v_today)
        )
        ON CONFLICT (reference) DO NOTHING;
    END IF;
END;
$$;


-- -----------------------------------------------------------------------------
-- credit_spend — charge for an action
--
-- Returns one row: whether it was allowed, the resulting balances, and what was
-- actually taken from each bucket.
--
-- Idempotent on p_reference. A replayed call — a retried request, a
-- double-clicked send — returns the original outcome and charges nothing more.
-- This is what makes it safe for the caller to retry on a network error, which
-- is the situation where double-charging otherwise happens.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION credit_spend(
    p_user_id   UUID,
    p_cost      INTEGER,
    p_action    VARCHAR,
    p_reference VARCHAR,
    p_daily     INTEGER
)
RETURNS TABLE (
    allowed       BOOLEAN,
    charged       INTEGER,
    free_left     INTEGER,
    paid_left     INTEGER,
    from_free     INTEGER,
    from_paid     INTEGER,
    already_spent BOOLEAN
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_free      INTEGER;
    v_paid      INTEGER;
    v_from_free INTEGER;
    v_from_paid INTEGER;
    v_existing  INTEGER;
BEGIN
    -- Replay check first, before anything is locked or moved.
    --
    -- Matched against the two exact suffixes rather than with LIKE. A pattern
    -- match would treat '%' or '_' inside a reference as a wildcard, and the
    -- failure mode is one spend suppressing an unrelated one.
    IF p_reference IS NOT NULL THEN
        SELECT COUNT(*) INTO v_existing
          FROM credit_ledger
         WHERE reference IN (p_reference || ':free', p_reference || ':paid')
           AND kind = 'SPEND';

        IF v_existing > 0 THEN
            SELECT u.free_credits, u.paid_credits INTO v_free, v_paid
              FROM users u WHERE u.id = p_user_id;
            RETURN QUERY SELECT TRUE, 0, COALESCE(v_free, 0), COALESCE(v_paid, 0), 0, 0, TRUE;
            RETURN;
        END IF;
    END IF;

    PERFORM credit_refresh_free(p_user_id, p_daily);

    SELECT u.free_credits, u.paid_credits
      INTO v_free, v_paid
      FROM users u
     WHERE u.id = p_user_id
       FOR UPDATE;

    IF NOT FOUND THEN
        RETURN QUERY SELECT FALSE, 0, 0, 0, 0, 0, FALSE;
        RETURN;
    END IF;

    IF v_free + v_paid < p_cost THEN
        RETURN QUERY SELECT FALSE, 0, v_free, v_paid, 0, 0, FALSE;
        RETURN;
    END IF;

    -- Free first. See the header for why the order is not arbitrary.
    v_from_free := LEAST(v_free, p_cost);
    v_from_paid := p_cost - v_from_free;

    UPDATE users
       SET free_credits = free_credits - v_from_free,
           paid_credits = paid_credits - v_from_paid
     WHERE id = p_user_id;

    -- One row per bucket touched, so no single row is ambiguous about which
    -- balance it moved. The reference is suffixed to keep both unique.
    IF v_from_free > 0 THEN
        INSERT INTO credit_ledger (user_id, kind, bucket, delta, balance_after, action, reason, reference)
        VALUES (p_user_id, 'SPEND', 'FREE', -v_from_free, v_free - v_from_free, p_action,
                format('%s (%s free credit(s))', p_action, v_from_free),
                p_reference || ':free');
    END IF;

    IF v_from_paid > 0 THEN
        INSERT INTO credit_ledger (user_id, kind, bucket, delta, balance_after, action, reason, reference)
        VALUES (p_user_id, 'SPEND', 'PAID', -v_from_paid, v_paid - v_from_paid, p_action,
                format('%s (%s paid credit(s))', p_action, v_from_paid),
                p_reference || ':paid');
    END IF;

    RETURN QUERY SELECT TRUE, p_cost, v_free - v_from_free, v_paid - v_from_paid,
                        v_from_free, v_from_paid, FALSE;
END;
$$;


-- -----------------------------------------------------------------------------
-- credit_grant — add credits to a bucket
--
-- Every inbound movement goes through here: signup bonus, admin grant, settled
-- purchase, refund. Idempotent on p_reference, which is what makes it safe to
-- call from a webhook handler that may be invoked more than once for one
-- payment.
--
-- Returns the new balance of the affected bucket, or the current one unchanged
-- when the reference was already applied.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION credit_grant(
    p_user_id   UUID,
    p_amount    INTEGER,
    p_kind      credit_entry_kind,
    p_bucket    credit_bucket,
    p_action    VARCHAR,
    p_reason    TEXT,
    p_reference VARCHAR,
    p_order_id  UUID DEFAULT NULL
)
RETURNS TABLE (
    applied   BOOLEAN,
    free_left INTEGER,
    paid_left INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_free INTEGER;
    v_paid INTEGER;
    v_new  INTEGER;
BEGIN
    IF p_amount <= 0 THEN
        SELECT u.free_credits, u.paid_credits INTO v_free, v_paid FROM users u WHERE u.id = p_user_id;
        RETURN QUERY SELECT FALSE, COALESCE(v_free, 0), COALESCE(v_paid, 0);
        RETURN;
    END IF;

    IF p_reference IS NOT NULL AND EXISTS (SELECT 1 FROM credit_ledger WHERE reference = p_reference) THEN
        SELECT u.free_credits, u.paid_credits INTO v_free, v_paid FROM users u WHERE u.id = p_user_id;
        RETURN QUERY SELECT FALSE, COALESCE(v_free, 0), COALESCE(v_paid, 0);
        RETURN;
    END IF;

    SELECT u.free_credits, u.paid_credits
      INTO v_free, v_paid
      FROM users u
     WHERE u.id = p_user_id
       FOR UPDATE;

    IF NOT FOUND THEN
        RETURN QUERY SELECT FALSE, 0, 0;
        RETURN;
    END IF;

    IF p_bucket = 'FREE' THEN
        v_new := v_free + p_amount;
        UPDATE users SET free_credits = v_new WHERE id = p_user_id;
        v_free := v_new;
    ELSE
        v_new := v_paid + p_amount;
        UPDATE users SET paid_credits = v_new WHERE id = p_user_id;
        v_paid := v_new;
    END IF;

    INSERT INTO credit_ledger (user_id, kind, bucket, delta, balance_after, action, reason, reference, order_id)
    VALUES (p_user_id, p_kind, p_bucket, p_amount, v_new, p_action, p_reason, p_reference, p_order_id);

    RETURN QUERY SELECT TRUE, v_free, v_paid;
END;
$$;


-- -----------------------------------------------------------------------------
-- credit_refund — give back what a specific spend took
--
-- A claim is a promise to deliver an answer, and delivery can still fail after
-- the charge: WhatsApp refuses the send, the model times out, the process dies
-- mid-reply. Charging for an answer that never arrived is the wrong side of
-- that trade, so the spend is reversed.
--
-- ## Why this reverses the ledger rows rather than adding a fixed amount
--
-- A spend can straddle both buckets — three free credits and one paid — and a
-- naive refund of "4 credits" has to guess where they go. Guessing wrong either
-- converts paid credits into free ones that expire at midnight (the advocate
-- silently loses money) or free ones into paid (we silently give it away).
--
-- Reading the original SPEND rows removes the guess entirely: each is reversed
-- into the bucket it actually came from, for exactly the amount it took.
--
-- Idempotent, like everything else here: the refund rows carry their own
-- references, so a retried refund finds them already present and does nothing.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION credit_refund(
    p_user_id   UUID,
    p_reference VARCHAR,
    p_reason    TEXT
)
RETURNS TABLE (
    refunded  INTEGER,
    free_left INTEGER,
    paid_left INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_entry    RECORD;
    v_total    INTEGER := 0;
    v_free     INTEGER;
    v_paid     INTEGER;
    v_new      INTEGER;
    v_ref      VARCHAR;
BEGIN
    SELECT u.free_credits, u.paid_credits
      INTO v_free, v_paid
      FROM users u
     WHERE u.id = p_user_id
       FOR UPDATE;

    IF NOT FOUND THEN
        RETURN QUERY SELECT 0, 0, 0;
        RETURN;
    END IF;

    FOR v_entry IN
        SELECT bucket, delta, reference
          FROM credit_ledger
         WHERE user_id = p_user_id
           AND kind = 'SPEND'
           AND reference IN (p_reference || ':free', p_reference || ':paid')
    LOOP
        v_ref := replace(v_entry.reference, 'spend:', 'refund:');
        -- Suffix guards the case where a reference was not prefixed 'spend:'.
        IF v_ref = v_entry.reference THEN
            v_ref := 'refund:' || v_entry.reference;
        END IF;

        CONTINUE WHEN EXISTS (SELECT 1 FROM credit_ledger WHERE reference = v_ref);

        -- delta is negative on a SPEND, so negating it is the amount returned.
        IF v_entry.bucket = 'FREE' THEN
            v_new  := v_free - v_entry.delta;
            UPDATE users SET free_credits = v_new WHERE id = p_user_id;
            v_free := v_new;
        ELSE
            v_new  := v_paid - v_entry.delta;
            UPDATE users SET paid_credits = v_new WHERE id = p_user_id;
            v_paid := v_new;
        END IF;

        INSERT INTO credit_ledger (user_id, kind, bucket, delta, balance_after, action, reason, reference)
        VALUES (p_user_id, 'REFUND', v_entry.bucket, -v_entry.delta, v_new, 'refund', p_reason, v_ref);

        v_total := v_total - v_entry.delta;
    END LOOP;

    RETURN QUERY SELECT v_total, v_free, v_paid;
END;
$$;


-- =============================================================================
-- Row level security
--
-- Same posture as 0005: the application connects as the owner and bypasses RLS,
-- and these policies exist so the intent is written down in the schema rather
-- than assumed. Everything here is either credentials or personal data, so
-- there is no public-read table among them.
-- =============================================================================
ALTER TABLE user_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE web_sessions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_tokens     ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_ledger   ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_orders   ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_events  ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_threads    ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages   ENABLE ROW LEVEL SECURITY;

-- FORCE so that even the table owner is subject to policy. Session tokens and
-- payment records are the two things in this schema where an accidental
-- unfiltered query is most expensive.
ALTER TABLE web_sessions   FORCE ROW LEVEL SECURITY;
ALTER TABLE auth_tokens    FORCE ROW LEVEL SECURITY;
ALTER TABLE credit_ledger  FORCE ROW LEVEL SECURITY;
ALTER TABLE credit_orders  FORCE ROW LEVEL SECURITY;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'user_identities', 'web_sessions', 'auth_tokens', 'credit_ledger',
        'credit_orders', 'payment_events', 'chat_threads', 'chat_messages'
    ]
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', t || '_service_all', t);
        EXECUTE format(
            'CREATE POLICY %I ON %I FOR ALL TO service_role USING (true) WITH CHECK (true)',
            t || '_service_all', t
        );
    END LOOP;
END $$;


-- =============================================================================
-- Backfill
--
-- Existing rows all arrived over WhatsApp, which is already the column default,
-- so signup_source needs nothing. The wallet does: every existing advocate
-- starts with an empty free bucket and no date, which credit_refresh_free()
-- reads as stale and fills on their next action. That is the correct outcome —
-- granting here would write a ledger row dated to the migration rather than to
-- the day the allowance was actually used.
-- =============================================================================

-- `daily_usage` and `claim_daily_quota()` are superseded by this ledger and are
-- no longer written to. They are deliberately NOT dropped: the rows are a real
-- record of what happened before this migration, and a DROP would destroy the
-- only copy of it to save a table nobody reads. Anything that needs historical
-- usage should read `daily_usage` for dates before the deployment of 0010 and
-- `credit_ledger` after it.
COMMENT ON TABLE daily_usage IS
    'SUPERSEDED by credit_ledger (migration 0010). Retained read-only for pre-0010 history; nothing writes here.';

COMMENT ON TABLE credit_ledger IS
    'Append-only record of every credit movement. Never UPDATE or DELETE a row; write a compensating entry instead.';
COMMENT ON TABLE credit_orders IS
    'Credit purchases. Amounts are integer PAISE, matching Razorpay. base_paise + tax_paise = amount_paise.';
COMMENT ON TABLE payment_events IS
    'Deduplicated gateway webhooks, keyed on the provider event id. Razorpay retries until 2xx.';
COMMENT ON COLUMN credit_ledger.reference IS
    'Idempotency key. UNIQUE, and supplied by every writer: daily:{user}:{date}, spend:{message}:{bucket}, order:{payment_id}.';
